name: "Gotecoli"
description: "Go Test Cover and Lint reports"
author: "Alice Di Nunno"

runs:
  using: 'composite'
  steps:
    - name: Install golangci-lint
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        echo "$HOME/go/bin" >> $GITHUB_PATH
      shell: bash
    - run: go mod tidy
      shell: bash
    - run: go run ./
      shell: bash

inputs:
  lint-args:
    description: "Extra arguments for golangci-lint"
    required: false
    default: ""

outputs:
  lint-result:
    description: "Result of the lint (e.g., pass/fail or summary)"

branding:
  icon: "check"
  color: "green"